#!/bin/bash
#based on https://www.tecmint.com/configure-ldap-client-to-connect-external-authentication/
#Some modifications to make it work!
#install ldap packages
apt-get --yes install libnss-ldap libpam-ldap ldap-utils nscd
//reset prompting
unset DEBIAN_FRONTEND
#installing ldap packages needed
sudo apt update && sudo apt install -y libnss-ldap libpam-ldap ldap-utils nscd
sudo auth-client-config -t nss -p lac_ldap
#Default values are fine
#sudo pam-auth-update
Not needed for automation
#vim /etc/pam.d/su
#add account file to line
echo "account sufficient pam_succeed_if.so uid = 0 use_uid quiet" >> /etc/pam.d/su
vim /etc/ldap/ldap.conf 
#Make some modification on ldap.conf for base and uri.
BASE    dc=nti310,dc=local
URI     ldap://ldap2
systemctl restart nscd
systemctl enable nscd
#need only for one machine, doesn't need automated:
#apt-get install  debconf-utils

apt-get update
apt-get install -y debconf-utils
export DEBIAN_FRONTEND=noninteractive
apt-get --yes install libnss-ldap libpam-ldap ldap-utils nscd
unset DEBIAN_FRONTEND 
sudo apt update && sudo apt install -y libnss-ldap libpam-ldap ldap-utils nscd
sudo auth-client-config -t nss -p lac_ldap
vim tempfile
ldap-auth-config        ldap-auth-config/rootbindpw     password
ldap-auth-config        ldap-auth-config/bindpw password
ldap-auth-config        ldap-auth-config/ldapns/base-dn string  dc=nti310,dc=local
ldap-auth-config        ldap-auth-config/binddn string  cn=proxyuser,dc=example,dc=net
ldap-auth-config        ldap-auth-config/pam_password   select  md5
ldap-auth-config        ldap-auth-config/ldapns/ldap-server     string  ldap://ldap2/
ldap-auth-config        ldap-auth-config/ldapns/ldap_version    select  3
ldap-auth-config        ldap-auth-config/dblogin        boolean false
ldap-auth-config        ldap-auth-config/rootbinddn     string  cn=ldapadm,dc=nti310,dc=local
ldap-auth-config        ldap-auth-config/move-to-debconf        boolean true
libpam-runtime  libpam-runtime/profiles multiselect     unix, ldap, systemd, capability
ldap-auth-config        ldap-auth-config/override       boolean true
ldap-auth-config        ldap-auth-config/dbrootlogin    boolean true
while read line; do echo "$line" | debconf-set-selections; done < tempfile
   
