#!/bin/bash
yum update -y && yum install -y rsyslog
systemctl start rsyslog
systemctl enable rsyslog
#we dont need to see status
systemctl status rsyslog
cp /etc/rsyslog.conf /etc/ryslog.conf.bak
vim /etc/rsyslog.conf
sed -i 's/#$ModLoad imudp/$ModLoad imudp/g' /etc/rsyslog.conf
sed -i 's/#$UDPServerRun 514/$UDPServerRun 514/g' /etc/rsyslog.conf
sed -i 's/#$ModLoad imtcp/$ModLoad imtcp/g' /etc/rsyslog.conf
sed -i 's/#$InputTCPServerRun 514/$InputTCPServerRun 514/g' /etc/rsyslog.conf
#add on this on ryslog.conf
#*.* ?RemoteLogs #no needed this line.
#check for listening the port
#sudo ss -tulnp | grep "rsyslog"
systemctl restart rsyslog


#Client automation on postgres
yum update -y && yum install -y rsyslog
systemctl start rsyslog
systemctl enable rsyslog
#backup file
cp /etc/rsyslog.conf /etc/ryslog.conf.bak
echo "*.* @@rsyslogserver:514" >> /etc/rsyslog.conf
systemctl restart rsyslog
#check this on rsyslog server 
tail -F /var/log/messages

#echo "test statement" | logger
